sequenceDiagram
    participant browser
    participant server

    browser-->server:POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of browser: {content: "nuevo texto", date: "2024-07-31T16:51:28.412Z"}
    activate server
    server-->>browser: {"message":"note created"}
    deactivate server
