POST http://localhost:3002/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salainen"
}

###

POST http://localhost:3002/api/users
Content-Type: application/json

{
  "username": "mellambias",
  "name": "Miguel Llambias",
  "password": "super123"
}