POST http://localhost:3002/api/notes HTTP/1.1
content-type: application/json

{
"content": "GET and POST are the most important methods of HTTP protocol",
"important": true
}

### Nota con usuario

POST http://localhost:3002/api/notes HTTP/1.1
content-type: application/json

{
"content": "User id of the note creator is at the start sent along de request",
"important": true,
"userId":"66c723d9652caa1d3ac9ef29"
}

### Nota con usuario

POST http://localhost:3002/api/notes HTTP/1.1
content-type: application/json

{
"content": "Another note of the same user",
"important": true,
"userId":"66c723d9652caa1d3ac9ef29"
}

### Nota con autorizacion

POST http://localhost:3002/api/notes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGxhbWJpYXMiLCJpZCI6IjY2YzcyM2Q5NjUyY2FhMWQzYWM5ZWYyOSIsImlhdCI6MTcyNDQxMDkyMn0.D9MUB5AeT3XrjosbWeaOEe-r3fA-ewFZppfIYSR9yaM

{
"content": "note of the user with Authorization: ",
"important": true,
"userId":"66c723d9652caa1d3ac9ef29"
}